/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TendersIndexRouteImport } from './routes/tenders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TendersIdRouteImport } from './routes/tenders.$id'
import { Route as AdminTendersRouteImport } from './routes/admin.tenders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as TendersStateStateRouteImport } from './routes/tenders.state.$state'
import { Route as TendersCategoryCategoryRouteImport } from './routes/tenders.category.$category'
import { Route as TendersStateStateDistrictRouteImport } from './routes/tenders.state.$state.$district'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIndexRoute = TendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TendersIdRoute = TendersIdRouteImport.update({
  id: '/tenders/$id',
  path: '/tenders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTendersRoute = AdminTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const TendersStateStateRoute = TendersStateStateRouteImport.update({
  id: '/tenders/state/$state',
  path: '/tenders/state/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersCategoryCategoryRoute = TendersCategoryCategoryRouteImport.update({
  id: '/tenders/category/$category',
  path: '/tenders/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersStateStateDistrictRoute =
  TendersStateStateDistrictRouteImport.update({
    id: '/$district',
    path: '/$district',
    getParentRoute: () => TendersStateStateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/tenders/$id': typeof TendersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tenders/': typeof TendersIndexRoute
  '/tenders/category/$category': typeof TendersCategoryCategoryRoute
  '/tenders/state/$state': typeof TendersStateStateRouteWithChildren
  '/tenders/state/$state/$district': typeof TendersStateStateDistrictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/tenders/$id': typeof TendersIdRoute
  '/admin': typeof AdminIndexRoute
  '/tenders': typeof TendersIndexRoute
  '/tenders/category/$category': typeof TendersCategoryCategoryRoute
  '/tenders/state/$state': typeof TendersStateStateRouteWithChildren
  '/tenders/state/$state/$district': typeof TendersStateStateDistrictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/tenders/$id': typeof TendersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tenders/': typeof TendersIndexRoute
  '/tenders/category/$category': typeof TendersCategoryCategoryRoute
  '/tenders/state/$state': typeof TendersStateStateRouteWithChildren
  '/tenders/state/$state/$district': typeof TendersStateStateDistrictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/admin/applications'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tenders'
    | '/tenders/$id'
    | '/admin/'
    | '/tenders/'
    | '/tenders/category/$category'
    | '/tenders/state/$state'
    | '/tenders/state/$state/$district'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/admin/applications'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tenders'
    | '/tenders/$id'
    | '/admin'
    | '/tenders'
    | '/tenders/category/$category'
    | '/tenders/state/$state'
    | '/tenders/state/$state/$district'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/admin/applications'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tenders'
    | '/tenders/$id'
    | '/admin/'
    | '/tenders/'
    | '/tenders/category/$category'
    | '/tenders/state/$state'
    | '/tenders/state/$state/$district'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  TendersIdRoute: typeof TendersIdRoute
  TendersIndexRoute: typeof TendersIndexRoute
  TendersCategoryCategoryRoute: typeof TendersCategoryCategoryRoute
  TendersStateStateRoute: typeof TendersStateStateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/': {
      id: '/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof TendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenders/$id': {
      id: '/tenders/$id'
      path: '/tenders/$id'
      fullPath: '/tenders/$id'
      preLoaderRoute: typeof TendersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenders': {
      id: '/admin/tenders'
      path: '/tenders'
      fullPath: '/admin/tenders'
      preLoaderRoute: typeof AdminTendersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenders/state/$state': {
      id: '/tenders/state/$state'
      path: '/tenders/state/$state'
      fullPath: '/tenders/state/$state'
      preLoaderRoute: typeof TendersStateStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/category/$category': {
      id: '/tenders/category/$category'
      path: '/tenders/category/$category'
      fullPath: '/tenders/category/$category'
      preLoaderRoute: typeof TendersCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/state/$state/$district': {
      id: '/tenders/state/$state/$district'
      path: '/$district'
      fullPath: '/tenders/state/$state/$district'
      preLoaderRoute: typeof TendersStateStateDistrictRouteImport
      parentRoute: typeof TendersStateStateRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTendersRoute: typeof AdminTendersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTendersRoute: AdminTendersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TendersStateStateRouteChildren {
  TendersStateStateDistrictRoute: typeof TendersStateStateDistrictRoute
}

const TendersStateStateRouteChildren: TendersStateStateRouteChildren = {
  TendersStateStateDistrictRoute: TendersStateStateDistrictRoute,
}

const TendersStateStateRouteWithChildren =
  TendersStateStateRoute._addFileChildren(TendersStateStateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  TendersIdRoute: TendersIdRoute,
  TendersIndexRoute: TendersIndexRoute,
  TendersCategoryCategoryRoute: TendersCategoryCategoryRoute,
  TendersStateStateRoute: TendersStateStateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
